package(default_visibility = ["//visibility:private"])

cc_binary(
    name = "basic",
    srcs = [
        "basic.cpp",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//alpaca:alpaca",
    ],
)