package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "view_account_info",
    srcs = ["view_account_info.cpp"],
    deps = ["//alpaca:alpaca"],
)

cc_binary(
    name = "view_portfolio_gain_loss",
    srcs = ["view_portfolio_gain_loss.cpp"],
    deps = ["//alpaca:alpaca"],
)

cc_binary(
    name = "get_list_of_assets",
    srcs = ["get_list_of_assets.cpp"],
    deps = ["//alpaca:alpaca"],
)

cc_binary(
    name = "see_if_asset_is_tradable",
    srcs = ["see_if_asset_is_tradable.cpp"],
    deps = ["//alpaca:alpaca"],
)

cc_binary(
    name = "check_if_market_is_open",
    srcs = ["check_if_market_is_open.cpp"],
    deps = ["//alpaca:alpaca"],
)

cc_binary(
    name = "place_new_orders",
    srcs = ["place_new_orders.cpp"],
    deps = ["//alpaca:alpaca"],
)

cc_binary(
    name = "use_client_order_ids",
    srcs = ["use_client_order_ids.cpp"],
    deps = ["//alpaca:alpaca"],
)

cc_binary(
    name = "list_existing_orders",
    srcs = ["list_existing_orders.cpp"],
    deps = ["//alpaca:alpaca"],
)

cc_binary(
    name = "view_open_positions",
    srcs = ["view_open_positions.cpp"],
    deps = ["//alpaca:alpaca"],
)

cc_binary(
    name = "run_stream_handler",
    srcs = ["run_stream_handler.cpp"],
    deps = ["//alpaca:alpaca"],
)

cc_binary(
    name = "get_historical_data",
    srcs = ["get_historical_data.cpp"],
    deps = ["//alpaca:alpaca"],
)